'use strict';
// Generates assets/js/asset-map.js (and its byte copy functions/_asset_map.js) from the
// owner-approved draft files (rules asset-map-v1-draft2 + copy asset-map-copy-v1-draft, D5 approved 2026-10-09).
// Usage: node tools/asset-map/build-module.cjs <rules.json> <copy.json>
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const [rulesFile,copyFile]=process.argv.slice(2);
const R=JSON.parse(fs.readFileSync(rulesFile,'utf8')),C=JSON.parse(fs.readFileSync(copyFile,'utf8'));
const Q=JSON.parse(fs.readFileSync(path.join(root,'data/questions.json'),'utf8'));
const qt={};(function walk(o){if(Array.isArray(o))o.forEach(walk);else if(o&&typeof o==='object'){if(o.id&&o.text&&/^Q/.test(o.id))qt[o.id]=o.text;Object.values(o).forEach(walk);}})(Q);
const rules={version:'asset-map-v1',order:R.order,weights:R.weights,minEvidence:R.minEvidence,minChoice:R.minChoice,
  choice:R.choice,likert:R.likert.map(l=>Object.assign({},l,{text:qt[l.q].replace(/\s*\(.*\)\s*$/,'')})),axisTop2:R.axisTop2,
  baseline:R.baseline,likertScores:Q.likertScores,
  probes:Object.fromEntries(Object.entries(R.probes).map(([k,v])=>[k,{fills:v.fills,text:C.probeText[k]}]))};
const copy={version:'asset-map-copy-v1',fixedLine:C.fixedLine,actions:C.actions,selfReportedLabel:C.selfReportedLabel,selfReportedNote:C.selfReportedNote,insufficient:C.insufficient,
  addMore:'다른 변화도 내 것 같다면 다이어리에서 직접 더할 수 있어요.'};
const src=`/* 인생포트폴리오 — 고유성 기반 자산화 길찾기 엔진 (asset-map v1).
 * GENERATED by tools/asset-map/build-module.cjs — do not edit by hand.
 * Rules asset-map-v1 (owner-approved D5, 2026-10-09) + customer copy asset-map-copy-v1.
 * Pure and deterministic: same answers + same rules version => same result. No network, no AI,
 * no free-text use, no ranking of people. Optional-question answers (D7 option C) are NEVER scored;
 * a "yes" is shown beside the result as the person's own words.
 * functions/_asset_map.js must stay a byte copy of this file (checked by test). */
(function (root, factory) {
  if (typeof module !== "undefined" && module.exports) module.exports = factory();
  else root.AssetMap = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  var RULES = ${JSON.stringify(rules)};
  var COPY = ${JSON.stringify(copy)};
  function arr(v) { return Array.isArray(v) ? v : (v == null || v === "" ? [] : [v]); }
  function compute(input) {
    var answers = (input && input.answers) || {}, axisRanking = (input && input.axisRanking) || [], probes = (input && input.probes) || {};
    var W = RULES.weights, order = RULES.order, acts = {};
    order.forEach(function (a) { acts[a] = { score: 0, choiceN: 0, refs: [], subs: {} }; });
    function add(a, sub, w, ref, isChoice) { var x = acts[a]; if (!x) return; x.score += w; x.refs.push(ref); if (isChoice) x.choiceN += 1; if (sub) x.subs[sub] = (x.subs[sub] || 0) + w; }
    RULES.choice.forEach(function (c) { if (arr(answers[c.q]).indexOf(c.opt) >= 0) c.to.forEach(function (t) { add(t[0], t[1], W.choice, { q: c.q, opt: c.opt }, true); }); });
    RULES.likert.forEach(function (l) { var v = answers[l.q]; var n = typeof v === "number" ? v : (RULES.likertScores[v] || null);
      if (n != null && n >= W.likertMin) l.to.forEach(function (t) { add(t[0], t[1], W.likert, { q: l.q, n: n }, false); }); });
    axisRanking.slice(0, 2).forEach(function (r) { (RULES.axisTop2[r && r.axis] || []).forEach(function (a) { add(a, null, W.axisTop2, { axis: r.axis }, false); }); });
    order.forEach(function (a) { acts[a].lift = acts[a].score / RULES.baseline[a]; });
    var ranked = order.map(function (a, i) { return { code: a, i: i, x: acts[a] }; })
      .filter(function (o) { return o.x.refs.length >= RULES.minEvidence && o.x.choiceN >= RULES.minChoice; })
      .sort(function (p, q) { return (q.x.lift - p.x.lift) || (q.x.choiceN - p.x.choiceN) || (p.i - q.i); });
    var actions = ranked.slice(0, 3).map(function (o) {
      var subs = Object.keys(o.x.subs).sort(function (s, t) { return (o.x.subs[t] - o.x.subs[s]) || (s < t ? -1 : s > t ? 1 : 0); });
      return { code: o.code, sub: subs[0] || null, evidence: o.x.refs.slice() }; });
    var thin = order.filter(function (a) { return acts[a].refs.length < RULES.minEvidence || acts[a].choiceN < RULES.minChoice; });
    var shown = actions.map(function (o) { return o.code; });
    var ask = Object.keys(RULES.probes).sort().filter(function (pid) { var f = RULES.probes[pid].fills; return order.indexOf(f) >= 0 && thin.indexOf(f) >= 0 && shown.indexOf(f) < 0; }).slice(0, 2);
    var selfReported = [];
    ask.forEach(function (pid) { var f = RULES.probes[pid].fills; if (probes[pid] === "yes" && selfReported.indexOf(f) < 0) selfReported.push(f); });
    return { version: RULES.version, actions: actions, selfReported: selfReported, ask: ask, insufficient: actions.length === 0 };
  }
  // Customer view: names, sentences and the person's own chosen answers only (no question numbers, no codes).
  function reason(e) {
    if (e.opt) return "고른 답 “" + e.opt + "”";
    if (e.n) { var l = RULES.likert.filter(function (x) { return x.q === e.q; })[0]; return "“" + (l ? l.text : "") + "” → " + (e.n >= 5 ? "매우 그렇다" : "그렇다"); }
    return null;
  }
  function view(result) {
    var items = result.actions.map(function (a, i) {
      var A = COPY.actions[a.code], S = a.sub ? A.subs[a.sub] : null;
      return { first: i === 0, name: A.name, line: A.line, summary: i === 0 ? A.summary : null, focus: S ? S.ko : null, firstStep: i === 0 && S ? S.first : null,
        reasons: a.evidence.map(reason).filter(Boolean).slice(0, 3) };
    });
    return { version: result.version, copy: COPY.version, items: items,
      self: result.selfReported.map(function (c) { return { name: COPY.actions[c].name, line: COPY.actions[c].line }; }),
      ask: result.ask.map(function (pid) { return { id: pid, text: RULES.probes[pid].text }; }),
      env: { id: "P5", text: RULES.probes.P5.text }, insufficient: result.insufficient ? COPY.insufficient : null,
      fixedLine: COPY.fixedLine, selfLabel: COPY.selfReportedLabel, selfNote: COPY.selfReportedNote, addMore: COPY.addMore };
  }
  return { VERSION: RULES.version, RULES: RULES, COPY: COPY, compute: compute, view: view };
});
`;
fs.writeFileSync(path.join(root,'assets/js/asset-map.js'),src);fs.writeFileSync(path.join(root,'functions/_asset_map.js'),src);
console.log('wrote asset-map.js',src.length,'bytes');
